### ISSUE TITLE
Feature Request: remove dependency on pthreads?

### ISSUE THREAD

**Issue by dicroce** [bendiken/lmdbxx#11]
I'd like to use lmdb++ but as it stands I cannot because of it's dependency on pthreads... The real problem is that on Windows it looks like the current code requires pthread_t from mingw and I am using Visual Studio on Windows. Since it requires a modern implementation of C++ anyway, might it be possible to use only standard features?

**Comment by dicroce** [comment]
Just realized lmdb itself has the same issue... So your use is probably fine.... Closing.

**Comment by artob** [comment]
Indeed, there is no explicit pthreads use in the LMDB++ header file.

**Comment by davidalbertonogueira** [comment]
@dicroce , how have you solved/handled that incompatibility of lmdb with Windows Visual Studio compilation? Have you ported/found anyone who did it?

**Comment by dicroce** [comment]
I ended up writing my own LMDB wrapper (https://github.com/dicroce/tables) so it didn't matter.
