### ISSUE TITLE
Example uses the same dbi instance with a different transaction

### ISSUE THREAD

**Issue by varung** [bendiken/lmdbxx#2]
In the example code provided in your Readme.MD, the second transaction uses the "dbi" instance that was opened using the first transaction:

    auto dbi = lmdb::dbi::open(wtxn, nullptr);
    ...
    auto cursor = lmdb::cursor::open(rtxn, dbi);

Is this recommended? Or should one open a new database for every transaction?

**Comment by bendiken** [comment]
LMDB database handles outlive transactions; see upstream's documentation for [`mdb_dbi_open()`](http://symas.com/mdb/doc/group__internal.html#gac08cad5b096925642ca359a6d6f0562a).

**Comment by varung** [comment]
It seems that the db handle outlives the transaction, iff it doesn't abort.
If it does abort, then the handle is closed. If I pass a closed handle to
an operation with a new transaction, what would happen? Does the DB used
with a transaction get closed if any transaction that uses it aborts, or
just the first one that created it?

Sorry to bother you: As a simpler interface, would it be reasonable to
always open the database again for every transaction I wish to perform? I
understand I must create a lock around the "open" call, since it is not
supposed to be called by multiple transactions at the same time?

What's the right way to use this library from a multithreaded program?
