### ISSUE TITLE
Querying for different types in key/value pair

### ISSUE THREAD

**Issue by Thazz** [bendiken/lmdbxx#4]
In my case, I'm storing key/value pairs as int/string.

The problem arises when I wan't to check if given pair exists in database. Currently I'm only able to check if given key exists via  lmdb::cursor::find. Is it somehow possible to do this for key/value pair?

**Comment by bendiken** [comment]
This question would be best addressed to the [LMDB mailing list](https://github.com/bendiken/lmdbxx#support). The lmdbxx project only provides a C++ binding to the underlying C API from LMDB, so any semantics the underlying library provides will be passed through as-is.
